version: "3"

services:
    db:
        image: "postgres:latest"
        environment:
            - POSTGRES_PASSWORD=postgres1
            - POSTGRES_USER=books_manager
            - POSTGRES_DB=books_db
        ports:
            - "5432:5432"